name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install linters
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck shfmt python3-flake8

      - name: shellcheck
        run: |
          set -e
          find . -type f -name "*.sh" -print0 | xargs -0 -I{} bash -lc 'shellcheck -x "{}"'

      - name: shfmt (check only)
        run: |
          set -e
          # enforce tabs=2, indent, simplify, POSIX shell format checks only
          find . -type f -name "*.sh" -print0 | xargs -0 shfmt -d -i 2 -ci -s

      - name: flake8
        run: |
          set -e
          if compgen -G "./**/*.py" > /dev/null; then
            python3 -m flake8 .
          else
            echo "No Python files; skipping flake8."
          fi
